# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f5b3ad63c9ac6116932ff0483bb26d09e418b084989dc04a82ae295a59fd971a5956cf4b696837b6d1373109ff6a7286b6ca56ab4e0a677ae51790c4b951ae9

test:
  secret_key_base: 5a0d2e0ae3005c1be7fa0dddb64bb4aaf71476cfbb1eb588249a0c8eb4304859afc53c3e57f59711c77bd78fef2c1dd180d0a568e82f5ae952bb98053fb6ab37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
